### ISSUE TITLE
Game fails to start with AtE enabled (CK2 at 2.6.1.1, AtE at 8.0)

### ISSUE THREAD

**Issue by Cruxador** [Ofaloaf/postapoc#103]
Gives a black screen, then disappears, when tried with all submods or just the face submods. Without submods, shows the Paradox logo splash screen then disappears. I have all DLC.

**Comment by romancapitalist** [comment]
ATE 8.0 runs fine on 2.6.1.1 on my machine, so it's probably an issue on your end. I know this is the cliché answer, but try a clean install and make absolutely sure no non-ATE mods are activated.

**Comment by Cruxador** [comment]
Well, I did the latter, and it works fine in vanilla or with other mods. I suppose I'll see what a clean install does when I get time at some point this week, and then report back.

**Comment by GSonderling** [comment]
Could we close this issue, we are already version ahead. It's not relevant.
