### ISSUE TITLE
african faces are invisible

### ISSUE THREAD

**Issue by thivus** [Ofaloaf/postapoc#104]
I just downloaded the newest version and the faces of african americans are completely invisible
![20160911201455_1](https://cloud.githubusercontent.com/assets/9995766/18423836/9699765a-785d-11e6-941b-68c49f1dcf13.jpg)
![20160911201822_1](https://cloud.githubusercontent.com/assets/9995766/18423837/97893cb2-785d-11e6-950e-68f7bb699877.jpg)
![20160911202316_1](https://cloud.githubusercontent.com/assets/9995766/18423838/98977b82-785d-11e6-9d0b-25275fdbb272.jpg)

**Comment by The-Celt** [comment]
You require the African portraits DLC. We've had bugs with this on occasion but currently all are resolved.
