### ISSUE TITLE
Rust Cultist crash in Miami Valley

### ISSUE THREAD

**Issue by finbikkifin** [Ofaloaf/postapoc#115]
Doing basically anything (trying to enact the Revoke Titles law, going on a salvage expedition) leads to an immediate crash to desktop as the Rust Cultist guy in Miami Valley.

Unfortunately I'm not at my computer, and spent most of my time assuming it was an issue with something else - I reinstalled ATE, redownloaded ATE, and generally messed around but other leaders (and the base game) were fine. 

The error log (from memory) had a bunch of junk about invalid events which seemed to be MNM events - I don't have the new DLC, though - and something about failure to find textures for the pagan interface. Again, sorry - away from computer, don't have the log, and I spent more time fiddling with other stuff that turned out to work fine than trying to find the exact cause. I'll try to update this with more information if I can.

I just wanna worship the omnissiah ;_;

**Comment by SteelyGlint** [comment]
I am able to reproduce this crash every time, but have not yet figured out the problem. The crash occurs when the salvage.1 event is triggered by the expedition decision, but that event hasn't changed so I don't know why it would suddenly start crashing. Crash occurs even if I remove all functionality from the salvage.1 options so they're completely blank.

**Comment by SteelyGlint** [comment]
Seems to be related to Rostmann culture, as it apparently occurs when an event appears for a ruler of that culture. Possibly related to displaying the event portrait.

**Comment by finbikkifin** [comment]
Praise the Omnissiah. After performing the ritual of "downloading the new version" and anointing my computer with the sacred unguents to appease the machine spirit, all seems well. I haven't had time to do much more than poke a few buttons, but it seems fixed. Thanks!
