### ISSUE TITLE
Every title has open succession and only open succession

### ISSUE THREAD

**Issue by Ghibelline** [Ofaloaf/postapoc#123]
I'm not sure if this is a personal issue because I merge all the addons and base into one folder, but it seems that every title, barring theocracies and merchant republics, is subject to open succession, even the Columbian Confederacy and tribal people.

**Comment by SteelyGlint** [comment]
Unknown cause. Introduced by changes in CK2 2.7.1.

**Comment by GSonderling** [comment]
This seams to be problem on your end, all inheritance works fine for me.

 Running 0.9 AtE on 2.7.1 CK2 all DLCs except for face/unit packs enabled.

**Comment by GSonderling** [comment]
Sorry, seems that I have the problem now as well. Good news is that I am working on a fix and I seem to be on right path.
Will updated later today.

**Comment by GSonderling** [comment]
Just submitted pull request.
