### ISSUE TITLE
blank message pop ups

### ISSUE THREAD

**Issue by lrdnelson** [Ofaloaf/postapoc#126]
i have been trying to play but every time i start about a month in 2 blank messages pop up and pause the game, and stop me from unpausing.

**Comment by Shadeoses** [comment]
Which character, what culture and religion?

**Comment by SteelyGlint** [comment]
Most likely an installation problem, since I don't think this is a widespread problem.

**Comment by SteelyGlint** [comment]
This is a common outcome of parse failures in event files. I am unable to reproduce the problem either with 0.9 or with the current Github version, so I'm going to close this bug report.
