### ISSUE TITLE
Duplicated message about fabricated claim

### ISSUE THREAD

**Issue by SteelyGlint** [Ofaloaf/postapoc#19]
Your chancellor informs you with two letters simultaneously that he fabricated a claim
I was playing as a patrician of La Paz when I first saw this

**Comment by SteelyGlint** [comment]
Was this a vanilla bug that has been resolved? I haven't seen it in a while, and I don't remember anyone fixing it in AtE.

**Comment by TheDwemerComrade** [comment]
I believe it was a base game bug.

**Comment by SteelyGlint** [comment]
I haven't seen it in long enough that with TheDwemerComrade saying it's a vanilla bug, I'm going to close it.
