### ISSUE TITLE
Voodoo Zombi "Puppetmaster" modifier

### ISSUE THREAD

**Issue by PapaMichael** [Ofaloaf/postapoc#36]
When zombieing a character as a Voodoo, the puppetmaster +100 modifier is set for -1 months, but this doesn't cause it to permanent, it vanishes as soon as the game is unpaused,

**Comment by SteelyGlint** [comment]
Caused by some opinion modifiers without default durations. I specified durations explicitly in the Zombify decision, and added default durations to most of the new opinion modifiers.
