### ISSUE TITLE
Distance and the College of Cardinals

### ISSUE THREAD

**Issue by Xam229** [Ofaloaf/postapoc#37]
Hello!
According to my brother, the College of Cardinals is a little bit bugged in that, one of his candidates is the leader for the next Cardinals, but he is too far away to interact with the Pope and so nothing happens.  According to him, the College was down to three Cardinals before he stopped funding his candidate and they started appointing other Cardinals.  He also cannot join Crusades or anything like that.  Just thought I should let you guys know if you wanted to do anything about that or whatever!  The mod is looking great though!

**Comment by thecookiemaker** [comment]
what province is your brothers capital? The sphere of influence is set at 700 base + 100 for being the same religion which is the inner circle. the outer circle shows an extra 100 if you are the same culture as the pope. I have highlighted the provinces that start out as catholic. the white one is St Louis where the pope is located. If you are outside the circle then you are to far to interact with the pope
![influence](https://cloud.githubusercontent.com/assets/12282981/8045940/4e4c1f76-0df4-11e5-91e2-437ef9b147d5.png)

**Comment by Xam229** [comment]
He is out in California, I figured it might be something like that.  Thank you for the quick reply though!

**Comment by SteelyGlint** [comment]
I think the map in the comment above as thoroughly answered this issue, so I'm going to close it.
