### ISSUE TITLE
Wrong modifier for Maritimer/Yankee retinues

### ISSUE THREAD

**Issue by romancapitalist** [Ofaloaf/postapoc#47]
The Gallowglass retinue is heavy infantry, but the combat strength modifier is for light infantry (discovered this while trying out new Occultist stuff - looks great!).

**Comment by SteelyGlint** [comment]
Everything seems to be heavy infantry as far as I can tell. Where are you seeing a mention of light infantry?

**Comment by SteelyGlint** [comment]
I didn't find anything that suggests this is actually a problem. Reopen this bug if you can show me exactly where you're seeing the issue.

**Comment by romancapitalist** [comment]
From 00_retinue_subunits:

RETTYPE_CUL_IRISH = 
{
	first_type = 1
	first_amount = 200
	
	potential = {
		is_nomadic = no
		OR = {
			culture = maritimer
			culture = yankee
		}
	}
	
	modifier = {
		light_infantry_offensive = 0.5
		light_infantry_defensive = 0.3
	}
}

Unit type 1 is heavy infantry, but the combat modifiers are light infantry.

**Comment by romancapitalist** [comment]
Might also want to revise those values downward, +0.5 off AND +0.3 def is an awful lot for heavy infantry.

**Comment by SteelyGlint** [comment]
Okay, I see what you're talking about now. 

I changed the unit type to heavy and reduced the bonuses to +0.4 off and +0.2 def.

**Comment by romancapitalist** [comment]
Thanks!
