### ISSUE TITLE
Empire of Cascadia Broken.

### ISSUE THREAD

**Issue by manosad** [Ofaloaf/postapoc#48]
On the title creation screen, the empire of cascadia appears as a barony named ???e_cascadia or something like that. it doesn't have the empires COA, instead it has a black shield with a question mark.

EDIT:http://imgur.com/1iupnJO
EDIT2: Found the problem (for real this time!). In cascadia.txt, line 1667, it should be "culture = salishan" instead of "culture = salish".

**Comment by SteelyGlint** [comment]
Fixed an encoding issue with the cascadia.txt titles file that I think were causing this. It should show up properly in the current version.
