### ISSUE TITLE
Dead people inviting people to visit Marian shrines

### ISSUE THREAD

**Issue by DarkNinja3141** [Ofaloaf/postapoc#49]
Someone who had an apparition and built a shrine has invited me to visit it. The only problem is that he has been dead for 20 years.

http://images.akamai.steamusercontent.com/ugc/700660204497863322/61A0240BFF3C927A1F6CDADC106FD3F9998A8694/

**Comment by SteelyGlint** [comment]
Kind a of a bad fix to this, I just removed the portrait of the character sending the letter so it's not sent by a dead man. Also noticed there was a marian apparition event that should have been hidden, so I hid it while making the hide_from change.

I may revisit this to find a way to show the current province owner in the letter.
