### ISSUE TITLE
Missing Icon for Bureaucratic Government 

### ISSUE THREAD

**Issue by DarkNinja3141** [Ofaloaf/postapoc#50]
I have noticed that the icon for the bureaucratic government kept switching between the other ones. I found the source of the problem; it is that in generalstuff.gfx, at the bottom where all the government icons are, there are none for the bureaucratic government (also none for the colonial government).
I made a feudal variant here for the bureaucratic government: https://drive.google.com/file/d/0BzV_5g4Ws5Y2Um9fSm5qZnY0VXc/view?usp=sharing

**Comment by SteelyGlint** [comment]
Thanks for pointing this out, I added your icon for bureaucratic govt and made one for colonial as well.
