### ISSUE TITLE
Game crashes when Loading Flags

### ISSUE THREAD

**Issue by Toastwolf** [Ofaloaf/postapoc#53]
I just got the new version of the mod and the mod crashes at the loading screen every time I try to boot it up. I tried redownloading the mod from Github but that didn't seem to work. In case it may be relevant my PC is running Windows 10.

**Comment by Toastwolf** [comment]
And nevermind I fixed it, the game was trying to load the Game of Thrones mod at the same time for some reason. Love what you guys are doing, keep it up, great mod.

**Comment by SteelyGlint** [comment]
Ok, I'll resolve this issue since you've fixed the problem.

**Comment by Beckg04** [comment]
I Have the Same problem and checked if i was running any other mods and there were none but ATE
