### ISSUE TITLE
Resolution of Sedevacantism

### ISSUE THREAD

**Issue by AbuDhabi** [Ofaloaf/postapoc#56]
There is contact with the Old World via British sailors. Therefore, it should be possible to determine the fate of the Papacy, but I didn't find anything acknowledging this. 

Some suggestions:
- Sedevacantists on the eastern coast, after coming into contact with British merchants, may send out an expedition or embassy back to the Old World, with British help perhaps, to ascertain what the current state of the Papacy is. 
- The outcome of success might be random - the Papacy may have been destroyed, and nothing left of Old World Catholicism, or it may still exist in some form, lead by the Pope in Rome (or in exile somewhere else).
- In case of destruction of the Papacy in the Old World, the Sedevacantists might reconcile with the mainline American Catholics via an event similar to mending the Great Schism - rulers and counties get offers to convert, most taking it.
- In case continuing existence of the Papacy, the Sedevacantists might get a Religious Head (unlandable King-level Pope) and gain the ability to interact with said Religious Head. In this case, the mainline American Catholics might get hit with schism-mending, or suffer a moral authority hit.

**Comment by DGoldDragon28** [comment]
I am working on that right now. When done, I will post a pull request from my fork. Standby.

**Comment by AbuDhabi** [comment]
Sweet! I await developments.

**Comment by SteelyGlint** [comment]
Events added a while back speculate on the fate of Old Rome. I don't think we'll be adding more detail.
