### ISSUE TITLE
The mountain terrain is fantastic

### ISSUE THREAD

**Issue by JoeyB2198** [Ofaloaf/postapoc#59]
I'm sorry to contact you like this, but I didn't know where else to do so directly. I've just loaded up the most recent version, and the mountains are mind-blowing. The attention to detail and graphic quality were just amazing, so good that I, who have never before written a review for such a thing, had to let you know here.

Thank you for investing your time and effort into this piece of art and keep up the good work.

**Comment by romancapitalist** [comment]
For future reference, the best place to make comments and suggestions is probably on the dedicated ATE forum on the Paradox website: [https://forum.paradoxplaza.com/forum/index.php?threads/after-the-end-a-post-apocalyptic-america-mod.831384/](url)
