### ISSUE TITLE
Government type updates for Conclave

### ISSUE THREAD

**Issue by SteelyGlint** [Ofaloaf/postapoc#64]
Bureaucratic and Colonial governments need custom titles (e.g. Hereditary Despotic Kingdom).

Probably other stuff too, let me know if you see something.

**Comment by SteelyGlint** [comment]
I added govt flavor text for both custom govtypes, but I suspect there's other stuff that needs to get added beyond that.

**Comment by Helrica** [comment]
The Airmen seem suited for a unique title. Military Despotic Kingdom? Despotic Military Division? Rust cultists and probably americanists in general, too.

**Comment by SteelyGlint** [comment]
Still open to suggestions for various religions, but I'm closing this issue.
