### ISSUE TITLE
Crashing on loading to main menu.

### ISSUE THREAD

**Issue by Lirisa** [Ofaloaf/postapoc#69]
I've been trying 0.6.1 for the mod version and for CK II I've been using 2.5.1.1 

I tried deactiving conclave, but that didn't do anything either.

Should I be using a different version of CKII?

**Comment by SteelyGlint** [comment]
AtE 0.6.1 is incompatible with CK2 2.5.1 or higher.

The current Github version will load in CK2 2.5.1 and higher, but we're still doing work to get it fully compatible before we release 0.7.
