### ISSUE TITLE
Nuevogranadino Name

### ISSUE THREAD

**Issue by DarkNinja3141** [Ofaloaf/postapoc#78]
One of the cultures in Colombia is called "Nuevogranadino", which I believe refers to New Granada, the  Spanish viceroyalty. From my current knowledge of Spanish (and looking up on google translate), the word would really be "Neogranadino". It's shorter and would be easier to say and wouldn't be as cut off in the province view as the original. Neogranadino shows up in google translate as originating from the viceroyalty of New Granada, but nuevogranadino would mean new granadan as in a granadan that was made recently, not from new granada. This same rule also applies with New Yorker. In Spanish, it's "neoyoquino".

**Comment by SteelyGlint** [comment]
I believe Shade renamed that culture Cartagenero already.
