### ISSUE TITLE
All Terrain is Plains

### ISSUE THREAD

**Issue by spiffyspaceman** [Ofaloaf/postapoc#81]
Was playing today and wondering why my classic "hide in the Appalachians when the Holy Columbian Confederacy attacks and force them to take me on in the mountains" strategy wasn't working as well as it could. Turns out, all the terrain is plains (which also explains why all my commanders very quickly became flatland commanders). Water crossings still register as water crossings though. Here are a couple screengrabs of places I think used to be something other than plains.

<img width="538" alt="screen shot 2016-03-15 at 2 45 10 pm" src="https://cloud.githubusercontent.com/assets/17860184/13791833/ef0c68e4-eabc-11e5-9088-f2a3e1b7fd2e.png">
<img width="831" alt="screen shot 2016-03-15 at 2 45 39 pm" src="https://cloud.githubusercontent.com/assets/17860184/13791834/ef101ed0-eabc-11e5-9814-ffddd2ce2e2c.png">

**Comment by SteelyGlint** [comment]
This is issue 65: https://github.com/Ofaloaf/postapoc/issues/65

I believe we have already fixed it in the current Github version, after a lot of tedious work.
