### ISSUE TITLE
Cetic, sagrado corazon, and Americanist religions not working in latest version

### ISSUE THREAD

**Issue by JoeyB2198** [Ofaloaf/postapoc#84]
Hi all,
 I'm having this issue with the 0.7 release. The religions are totally blacked out and characters of those religions are marked as noreligion. I've poked my head into the religion and history files but cannot find anything amiss.

http://i.imgur.com/VMPu5zn.jpg

**Comment by SteelyGlint** [comment]
Probably an installation issue of some sort, because no one else is seeing it. Try a full reinstall, deleting the existing version.

**Comment by Cooliodex** [comment]
I'm having this same problem. I downloaded it directly from this website...
