### ISSUE TITLE
Missing localization files?

### ISSUE THREAD

**Issue by Lprsti99** [Ofaloaf/postapoc#85]
Downloaded 0.7, and while the descriptions for the different areas (i.e. Ghosts of the North) show up just fine, the descriptions for the characters themselves just show some variation of ERA_CHAR_INFO (One of them was ERA_CHAR_INFO_1997018).

**Comment by SteelyGlint** [comment]
We haven't written descriptions for most of the characters. Only a couple emperors actually have anything written about them.
