### ISSUE TITLE
Quorum of the Twelve not using Papal Succession

### ISSUE THREAD

**Issue by VoltSpark** [Ofaloaf/postapoc#87]
Right now the Mormon religion having a College of Cardinals is completely pointless because the Presidency is using Open Elective rather than Papal Succession.

**Comment by SteelyGlint** [comment]
Hmm, I'm not sure what to do about this. I'm concerned that simply using papal succession would cause problems for Catholics or do other weird things that I don't expect.

**Comment by VoltSpark** [comment]
Considering that giving k_ursuline papal_succession didn't break the Catholics, I wouldn't think fixing it for the Mormons would break anything.

As for why this problem doesn't exist in vanilla with the Fraticelli, I think it's due to the Fraticelli Papacy being instituted by event.

**Comment by SteelyGlint** [comment]
Quorum of the Twelve should now use the proper succession. I'd appreciate it if you could do some testing to make sure it works properly. I just changed the succession laws, not anything related to the Mormon equivalent of anti-popes or other events (plots, CBs, etc.) Also, some things like "College of Cardinals" seem to be hardcoded, or at least we don't know how to change the localization for Mormons without also changing it for Catholics.

FYI, k_ursuline has replaced d_fraticelli in many After the End scripts.
