### ISSUE TITLE
Pagan heads of religions cannot become bankers

### ISSUE THREAD

**Issue by kwantamphlux** [Ofaloaf/postapoc#88]
banking_decisions file says 
`# Pope isn't a banker`
next to the head of religion restriction, but a reformed pagan religion wouldn't (necessarily) follow the same rules.

Maybe change
```
NOT = {
				AND = {
					controls_religion = yes # Pope isn't a banker
					NOT = { religion_group = oldworld } # Americanists and Consumerists okay with moneylending
				}
			}
```
to something like
```
NOT = {
				AND = {
					controls_religion = yes # Pope isn't a banker
					religion_group = christian
				}
			}
```
unless this is intentional.

**Comment by SteelyGlint** [comment]
Maybe something like this would work, to specifically include pagan religious heads:

`OR = {
	controls_religion = no			# any secular ruler
	religion_group = oldworld		# Americanists and Consumerists okay with moneylending
	religion_group = pagan_group	# reformed pagans also okay with it
}`

**Comment by SteelyGlint** [comment]
This change has been added, so I'll close this issue. Re-open it if there's still a problem.
