### ISSUE TITLE
Crash to desktop every few months

### ISSUE THREAD

**Issue by rspeer** [Ofaloaf/postapoc#96]
I have a game where I'm playing as an Americanist dynasty who have formed the Old Dominion. Around 2747 the game has become very unstable, crashing to desktop randomly every few months. I set it to autosave every months, but this is quite frustrating.

Playing on Windows, with Conclave, Legacy of Rome, Rajas of India, Sons of Abraham, The Old Gods, The Republic, The Sword of Islam, and Way of Life DLC installed.

I recognize that this is basically no information to base a bug report on, so could you tell me what other information I should provide? For example, is there a log file somewhere I should look for? Should I upload my save file somewhere?

**Comment by rspeer** [comment]
It's crashing about once a month now. I've found how to get a crash log. Here's my `error.txt` from one time that it crashed, with several thousand repetitive "invalid culture" lines skipped:

http://pastebin.com/30LZninq

**Comment by SteelyGlint** [comment]
Multiple new versions since this bug was created, in which many crashes have been fixed. Hopefully we addressed this one, but this bug is a bit stale so I'm going to close it.
