### ISSUE TITLE
Requesting permission to view your code as reference

### ISSUE THREAD

**Issue by GNY-001F2** [Ofaloaf/postapoc#97]
Hello,

We're trying to make a new total conversion mod where the entire map is a single city.

https://github.com/TheCityModTeam

We were wondering if it would be okay with you guys if we look at your work for reference. Most of us are new to CK2 modding.

Thanks!

**Comment by SteelyGlint** [comment]
I remember reading about that mod concept a few months ago, it seemed like an interesting idea.

Of course you can look at our work. It's one of the reasons we made this repo publicly visible. 

With proper attribution, you could even include portions of our work in your mod... although I'm not sure there's much in AtE that would be directly useful to you in that way.

**Comment by GNY-001F2** [comment]
Thanks!

If we were to copy your code we would definitely give you full credit for your work.

However I see that you guys don't have any license attached to your work. I was thinking of releasing our mod under the GPL or MIT license (for code; art may have different rules) because that gives specific permissions on how to reuse our work. We can't copy any of your work if you guys are not okay with your work being released under any of those licenses. So it would be nice to have some clarification here.
