### ISSUE TITLE
Occultist "Supreme Orient" title bug

### ISSUE THREAD

**Issue by Ax1008** [Ofaloaf/postapoc#98]
After reforming the faith I created the Supreme Orient title. While I hold the title my government type becomes "No Government", weakening all my holdings and causing all of my vassals to consider me a different government type.

**Comment by SteelyGlint** [comment]
That title is not meant to be controlled by the player. Did you conspire to seize control of it, or did it naturally fall into your hands?

**Comment by Ax1008** [comment]
Well I may have had to off the previous one, but I could create it normally once he became unlanded
